# Generated by Django 5.2.7 on 2025-10-29 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('concert', 'Concert'), ('meet_greet', 'Meet & Greet'), ('fanmeeting', 'Fan Meeting'), ('livestream', 'Live Stream'), ('premiere', 'Premiere'), ('workshop', 'Workshop'), ('charity', 'Charity Event'), ('virtual', 'Virtual Event'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='draft', max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('cover_image', models.ImageField(upload_to='events/covers/')),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('map_link', models.URLField(blank=True)),
                ('streaming_link', models.URLField(blank=True)),
                ('online_link', models.URLField(blank=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('doors_open', models.DateTimeField(blank=True, null=True)),
                ('total_capacity', models.IntegerField(default=0)),
                ('total_tickets', models.IntegerField(default=0)),
                ('available_tickets', models.IntegerField(default=0)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateTimeField(blank=True, null=True)),
                ('has_multiple_tiers', models.BooleanField(default=False)),
                ('min_age', models.IntegerField(default=0)),
                ('is_adult_only', models.BooleanField(default=False)),
                ('special_requirements', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('fan_club_exclusive', models.BooleanField(default=False)),
                ('fan_club_presale', models.BooleanField(default=False)),
                ('presale_start', models.DateTimeField(blank=True, null=True)),
                ('interested_count', models.IntegerField(default=0)),
                ('going_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(limit_choices_to={'user_type': 'celebrity'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_type', models.CharField(choices=[('interested', 'Interested'), ('going', 'Going'), ('maybe', 'Maybe')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('venue_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('organization_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('verified_attendee', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('max_per_person', models.IntegerField(default=4)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('includes_merchandise', models.BooleanField(default=False)),
                ('includes_meet_greet', models.BooleanField(default=False)),
                ('sale_start', models.DateTimeField()),
                ('sale_end', models.DateTimeField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event')),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ticket_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('booking_status', models.CharField(default='pending', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True)),
                ('dietary_requirements', models.CharField(blank=True, max_length=200)),
                ('checked_in', models.BooleanField(default=False)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to=settings.AUTH_USER_MODEL)),
                ('ticket_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventtickettier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('general', 'General Update'), ('schedule', 'Schedule Change'), ('venue', 'Venue Change'), ('tickets', 'Ticket Update'), ('cancellation', 'Cancellation'), ('postponement', 'Postponement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='events.event')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['celebrity', 'status'], name='events_even_celebri_6c4cad_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'status'], name='events_even_start_d_750395_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinterest',
            index=models.Index(fields=['event', 'interest_type'], name='events_even_event_i_76cd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinterest',
            index=models.Index(fields=['user', '-created_at'], name='events_even_user_id_45b6c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventinterest',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventreview',
            index=models.Index(fields=['event', '-created_at'], name='events_even_event_i_394937_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreview',
            index=models.Index(fields=['verified_attendee', '-helpful_count'], name='events_even_verifie_b52de0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreview',
            unique_together={('event', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['event', 'attendee'], name='events_even_event_i_6775a7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_926c72_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['booking_reference'], name='events_even_booking_b1b545_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['booking_code'], name='events_even_booking_a6b117_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['status'], name='events_even_status_8f844b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventupdate',
            index=models.Index(fields=['event', '-created_at'], name='events_even_event_i_914ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventupdate',
            index=models.Index(fields=['is_urgent', '-created_at'], name='events_even_is_urge_3240c8_idx'),
        ),
    ]
