# Generated by Django 5.2.7 on 2025-11-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='fanclub_celebrity',
            field=models.ForeignKey(blank=True, help_text='Celebrity who owns this fanclub - only they can post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanclub_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_fanclub',
            field=models.BooleanField(default=False),
        ),
    ]
