# Generated by Django 5.2.7 on 2025-10-29 17:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Celebrity Category',
                'verbose_name_plural': 'Celebrity Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='celebrities_is_acti_aec618_idx')],
            },
        ),
        migrations.CreateModel(
            name='CelebrityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('actor', 'Actor'), ('singer', 'Singer'), ('rapper', 'Rapper'), ('comedian', 'Comedian'), ('athlete', 'Athlete'), ('influencer', 'Influencer'), ('model', 'Model'), ('musician', 'Musician'), ('dancer', 'Dancer'), ('other', 'Other')], max_length=50)),
                ('bio_extended', models.TextField(blank=True, max_length=2000)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_documents', models.JSONField(default=list)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subscription_description', models.TextField(blank=True)),
                ('payment_methods', models.JSONField(default=dict)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('total_views', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='celebrity_profiles', to='celebrities.celebritycategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_celebrities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user__points'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('license', 'License'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc/')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='celebrities.celebrityprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_records', to='celebrities.celebrityprofile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_celebrities', through='celebrities.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CelebrityEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('subscription', 'Subscription'), ('event', 'Event'), ('merchandise', 'Merchandise'), ('donation', 'Donation'), ('other', 'Other')], max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='celebrities.celebrityprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['celebrity', '-created_at'], name='celebrities_celebri_607f0c_idx'), models.Index(fields=['source_type'], name='celebrities_source__c05e86_idx')],
            },
        ),
        migrations.CreateModel(
            name='CelebrityContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('article', 'Article'), ('livestream', 'Live Stream'), ('document', 'Document')], max_length=20)),
                ('access_level', models.CharField(choices=[('free', 'Free'), ('followers', 'Followers Only'), ('subscribers', 'Subscribers Only'), ('premium', 'Premium Subscribers'), ('vip', 'VIP Only')], default='free', max_length=20)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='celebrity_content/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='celebrity_content/thumbnails/')),
                ('external_url', models.URLField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('article_content', models.TextField(blank=True)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('preview_duration', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_content', to='celebrities.celebrityprofile')),
            ],
            options={
                'verbose_name': 'Celebrity Content',
                'verbose_name_plural': 'Celebrity Content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['celebrity', 'is_published'], name='celebrities_celebri_7508de_idx'), models.Index(fields=['content_type', 'access_level'], name='celebrities_content_859d07_idx'), models.Index(fields=['-published_at'], name='celebrities_publish_ebfa58_idx'), models.Index(fields=['is_featured', '-views_count'], name='celebrities_is_feat_025629_idx')],
            },
        ),
        migrations.CreateModel(
            name='CelebrityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('profile_views', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('new_followers', models.IntegerField(default=0)),
                ('lost_followers', models.IntegerField(default=0)),
                ('likes_received', models.IntegerField(default=0)),
                ('comments_received', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_subscribers', models.IntegerField(default=0)),
                ('lost_subscribers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='celebrities.celebrityprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['celebrity', '-date'], name='celebrities_celebri_aa4cd5_idx')],
                'unique_together': {('celebrity', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CelebrityAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('achievement_type', models.CharField(choices=[('followers', 'Followers Milestone'), ('posts', 'Posts Milestone'), ('earnings', 'Earnings Milestone'), ('engagement', 'Engagement Milestone'), ('special', 'Special Achievement')], max_length=50)),
                ('threshold', models.IntegerField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('points_reward', models.IntegerField(default=0)),
                ('badge_color', models.CharField(default='gold', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='celebrities.celebrityprofile')),
            ],
            options={
                'ordering': ['threshold'],
                'unique_together': {('celebrity', 'achievement_type', 'threshold')},
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='celebrities_status_5f9eb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'celebrity')},
        ),
        migrations.AddIndex(
            model_name='celebrityprofile',
            index=models.Index(fields=['category', 'verification_status'], name='celebrities_categor_1e4fad_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrityprofile',
            index=models.Index(fields=['-total_earnings'], name='celebrities_total_e_acb5f3_idx'),
        ),
    ]
