# Generated by Django 5.2.7 on 2025-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
