# Generated by Django 5.2.7 on 2025-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_celebritycontent_last_verification_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityprofile',
            name='document_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
