# Generated by Django 5.2.7 on 2025-11-11 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_celebrityprofile_document_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityprofile',
            name='allow_fan_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='auto_approve_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='custom_theme',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='exclusive_content_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='moderation_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='product_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='subscription_tiers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='subscription_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='celebrityprofile',
            index=models.Index(fields=['moderation_level'], name='celebrities_moderat_ca0f91_idx'),
        ),
    ]
