# Generated by Django 5.2.7 on 2025-11-12 16:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0005_celebrityprofile_allow_fan_posts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('esewa_id', models.CharField(blank=True, max_length=20)),
                ('esewa_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CelebrityKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('voter_id', 'Voter ID')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_front', models.ImageField(upload_to='kyc/documents/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/documents/')),
                ('selfie_with_document', models.ImageField(upload_to='kyc/selfies/')),
                ('proof_of_profession', models.FileField(blank=True, null=True, upload_to='kyc/profession/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CelebritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_publish_schedule', models.JSONField(default=dict, help_text='Schedule for auto-publishing content')),
                ('draft_reminders', models.BooleanField(default=True)),
                ('content_calendar_enabled', models.BooleanField(default=True)),
                ('auto_thank_new_subscribers', models.BooleanField(default=True)),
                ('welcome_message_template', models.TextField(blank=True, max_length=500)),
                ('birthday_greetings_enabled', models.BooleanField(default=True)),
                ('weekly_analytics_email', models.BooleanField(default=True)),
                ('monthly_revenue_report', models.BooleanField(default=True)),
                ('competitor_analysis', models.BooleanField(default=False)),
                ('ai_content_suggestions', models.BooleanField(default=True)),
                ('ai_response_assistant', models.BooleanField(default=False)),
                ('sentiment_monitoring', models.BooleanField(default=True)),
                ('third_party_integrations', models.JSONField(default=dict)),
                ('api_access_enabled', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Celebrity Settings',
                'verbose_name_plural': 'Celebrity Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='celebrityachievement',
            options={'ordering': ['is_unlocked', '-unlocked_at']},
        ),
        migrations.AlterModelOptions(
            name='celebritycontent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='celebrityprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='celebritycontent',
            name='celebrities_celebri_7508de_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebritycontent',
            name='celebrities_content_859d07_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebritycontent',
            name='celebrities_publish_ebfa58_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebritycontent',
            name='celebrities_is_feat_025629_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebrityearning',
            name='celebrities_source__c05e86_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebrityprofile',
            name='celebrities_categor_1e4fad_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebrityprofile',
            name='celebrities_total_e_acb5f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='celebrityprofile',
            name='celebrities_moderat_ca0f91_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='celebrities_status_5f9eb1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='celebrityachievement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='comments_received',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='engagement_rate',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='likes_received',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='lost_subscribers',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='new_subscribers',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='profile_views',
        ),
        migrations.RemoveField(
            model_name='celebrityanalytics',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='last_verification_attempt',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='verification_attempts',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='verification_rejection_reasons',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='celebritycontent',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='celebrityearning',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='document_submitted_at',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='subscription_fee',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='total_posts',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='verification_documents',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='event_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='events_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='exclusive_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='merchandise_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='post_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='post_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='posts_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='products_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='profile_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='subscription_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='tips_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityanalytics',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityearning',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='achievements',
            field=models.JSONField(default=list, help_text='List of achievements'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='allow_direct_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='allow_video_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='auto_ban_threshold',
            field=models.IntegerField(default=5, help_text='Number of violations before auto-ban'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='bank_account_details',
            field=models.JSONField(default=dict, help_text='Encrypted bank details'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='blocked_words',
            field=models.JSONField(default=list, help_text='Custom list of blocked words'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='comment_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='default_subscription_price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='dm_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for DM if > 0', max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='event_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='event_cancellation_policy',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='exclusive_content_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='fan_post_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='max_product_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='min_event_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='payout_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='profile_layout',
            field=models.CharField(choices=[('default', 'Default'), ('grid', 'Grid Layout'), ('timeline', 'Timeline Layout'), ('magazine', 'Magazine Layout')], default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='shipping_regions',
            field=models.JSONField(default=list, help_text='Regions where shipping is available'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='show_engagement_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='show_follower_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='show_trending_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='social_links',
            field=models.JSONField(default=dict, help_text='Social media links'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='subscription_benefits',
            field=models.JSONField(default=list, help_text='List of subscription benefits'),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='total_subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='video_call_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='celebrityachievement',
            name='achievement_type',
            field=models.CharField(choices=[('followers', 'Follower Milestone'), ('earnings', 'Earnings Milestone'), ('posts', 'Content Milestone'), ('engagement', 'Engagement Milestone'), ('special', 'Special Achievement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='celebrityachievement',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebrityachievement',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='celebrityachievement',
            name='threshold',
            field=models.IntegerField(help_text='Threshold value to unlock'),
        ),
        migrations.AlterField(
            model_name='celebrityanalytics',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('subscribers', 'Subscribers Only'), ('premium', 'Premium Tier'), ('vip', 'VIP Only')], default='subscribers', max_length=20),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('article', 'Article'), ('live', 'Live Stream')], max_length=20),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='celebritycontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='content_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='celebrityearning',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebrityearning',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='celebrityearning',
            name='source_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('merchandise', 'Merchandise'), ('event', 'Event'), ('tip', 'Tip'), ('message', 'Paid Message'), ('content', 'Premium Content')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='categories',
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='custom_theme',
            field=models.JSONField(default=dict, help_text='Custom theme colors and styles'),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='moderation_level',
            field=models.CharField(choices=[('low', 'Low - Basic filtering'), ('medium', 'Medium - Standard moderation'), ('high', 'High - Strict moderation'), ('custom', 'Custom rules')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='payment_methods',
            field=models.JSONField(default=list, help_text='Accepted payment methods'),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='product_categories',
            field=models.JSONField(default=list, help_text='Allowed product categories'),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='subscription_tiers',
            field=models.JSONField(default=dict, help_text='Custom subscription tiers with pricing'),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='celebrityprofile',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_celebrities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('voter_id', 'Voter ID')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], default='esewa', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='celebritycontent',
            index=models.Index(fields=['celebrity', '-created_at'], name='celebrities_celebri_bd6cde_idx'),
        ),
        migrations.AddIndex(
            model_name='celebritycontent',
            index=models.Index(fields=['is_published', '-published_at'], name='celebrities_is_publ_a66eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrityprofile',
            index=models.Index(fields=['verification_status'], name='celebrities_verific_cbcace_idx'),
        ),
        migrations.AddIndex(
            model_name='celebrityprofile',
            index=models.Index(fields=['user'], name='celebrities_user_id_42acf3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscriber', 'status'], name='celebrities_subscri_240f18_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['celebrity', 'status'], name='celebrities_celebri_91da36_idx'),
        ),
        migrations.AddField(
            model_name='celebritybankaccount',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celebritykyc',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celebritykyc',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celebritysettings',
            name='celebrity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='celebrityachievement',
            name='badge_color',
        ),
        migrations.RemoveField(
            model_name='celebrityachievement',
            name='points_reward',
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='categories',
            field=models.JSONField(default=list, help_text='List of celebrity categories'),
        ),
        migrations.AlterUniqueTogether(
            name='celebritykyc',
            unique_together={('celebrity', 'document_type', 'document_number')},
        ),
    ]
