# Generated by Django 5.2.7 on 2025-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0006_celebritybankaccount_celebritykyc_celebritysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityachievement',
            name='points_reward',
            field=models.IntegerField(default=0),
        ),
    ]
