# Generated by Django 5.2.7 on 2025-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0007_celebrityachievement_points_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityprofile',
            name='document_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='needs_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='celebrityprofile',
            name='resubmission_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
