# Generated by Django 5.2.7 on 2025-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0008_celebrityprofile_document_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from SubAdmin during verification'),
        ),
    ]
