# Generated by Django 5.2.7 on 2025-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0009_celebrityprofile_verification_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('voter_id', 'Voter ID'), ('proof_of_address', 'Proof of Address'), ('professional_certificate', 'Professional Certificate'), ('other', 'Other')], max_length=30),
        ),
    ]
