# Generated by Django 5.2.7 on 2025-11-04 15:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_date_range', models.IntegerField(default=30)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('critical_alert_threshold', models.IntegerField(default=10)),
                ('email_critical_alerts', models.BooleanField(default=True)),
                ('sms_critical_alerts', models.BooleanField(default=False)),
                ('auto_generate_reports', models.BooleanField(default=True)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('show_ai_insights', models.BooleanField(default=True)),
                ('show_predictions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Dashboard Settings',
                'verbose_name_plural': 'Admin Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='MANTRA', max_length=100)),
                ('platform_tagline', models.CharField(default='Connect with your favorite celebrities', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('max_posts_per_day', models.IntegerField(default=10)),
                ('max_messages_per_day', models.IntegerField(default=100)),
                ('max_file_upload_size', models.IntegerField(default=10)),
                ('auto_ban_threshold', models.IntegerField(default=5)),
                ('toxicity_threshold', models.FloatField(default=0.7)),
                ('spam_threshold', models.FloatField(default=0.6)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('enable_ai_moderation', models.BooleanField(default=True)),
                ('enable_recommendations', models.BooleanField(default=True)),
                ('enable_sentiment_analysis', models.BooleanField(default=True)),
                ('available_regions', models.JSONField(default=list)),
                ('supported_languages', models.JSONField(default=list)),
                ('points_config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_ban', 'User Ban'), ('user_unban', 'User Unban'), ('user_verify', 'User Verification'), ('content_delete', 'Content Deletion'), ('subadmin_create', 'SubAdmin Created'), ('subadmin_delete', 'SubAdmin Deleted'), ('config_change', 'Configuration Change'), ('data_export', 'Data Export'), ('system_restart', 'System Restart'), ('emergency_action', 'Emergency Action')], max_length=50)),
                ('description', models.TextField()),
                ('target_object_type', models.CharField(blank=True, max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='admin_dashb_admin_u_007345_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_dashb_action__67f57f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('users', 'User Data'), ('content', 'Content Data'), ('analytics', 'Analytics Data'), ('financial', 'Financial Data'), ('full', 'Full System Export')], max_length=20)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel'), ('sql', 'SQL Dump')], max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('encrypted', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='admin_dashb_request_45b19b_idx'), models.Index(fields=['status', '-created_at'], name='admin_dashb_status_726789_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('content', 'Content'), ('financial', 'Financial'), ('user', 'User Activity'), ('system', 'System')], max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('affected_users', models.IntegerField(default=0)),
                ('affected_regions', models.JSONField(default=list)),
                ('additional_data', models.JSONField(default=dict)),
                ('auto_resolve', models.BooleanField(default=False)),
                ('auto_resolve_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_system_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-level', '-created_at'],
                'indexes': [models.Index(fields=['level', 'is_resolved', '-created_at'], name='admin_dashb_level_3e466d_idx'), models.Index(fields=['category', '-created_at'], name='admin_dashb_categor_ee0b8e_idx')],
            },
        ),
    ]
