# Generated by Django 5.2.7 on 2025-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
