# Generated by Django 5.2.7 on 2025-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclubs', '0002_fanclub_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanclub',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
