# Generated by Django 5.2.7 on 2025-12-25 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclubs', '0003_fanclub_is_official'),
        ('messaging', '0002_add_fanclub_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fanclub',
            index=models.Index(fields=['celebrity', 'is_official'], name='fanclubs_fa_celebri_436673_idx'),
        ),
        migrations.AddConstraint(
            model_name='fanclub',
            constraint=models.UniqueConstraint(condition=models.Q(('is_official', True)), fields=('celebrity', 'is_official'), name='unique_official_fanclub_per_celebrity'),
        ),
    ]
