# Generated by Django 5.2.7 on 2025-10-29 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('merchandise_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_session_duration', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_p_date_16622d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_likes_given', models.IntegerField(default=0)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('influence_score', models.FloatField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_session_duration', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('mutual_connections', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-engagement_score'],
            },
        ),
    ]
