# Generated by Django 5.2.7 on 2025-11-04 15:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_handled_today', models.IntegerField(default=0)),
                ('kyc_verified_today', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('reports_handled_week', models.IntegerField(default=0)),
                ('kyc_verified_week', models.IntegerField(default=0)),
                ('false_positive_rate', models.FloatField(default=0)),
                ('reports_handled_month', models.IntegerField(default=0)),
                ('kyc_verified_month', models.IntegerField(default=0)),
                ('user_satisfaction_score', models.FloatField(default=0)),
                ('total_reports_handled', models.IntegerField(default=0)),
                ('total_kyc_verified', models.IntegerField(default=0)),
                ('total_warnings_issued', models.IntegerField(default=0)),
                ('total_bans_issued', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0)),
                ('appeal_overturn_rate', models.FloatField(default=0)),
                ('last_calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('subadmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_reports_handled'],
            },
        ),
        migrations.CreateModel(
            name='ModeratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('message', 'Message'), ('profile', 'Profile')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('original_content', models.TextField()),
                ('moderation_action', models.CharField(choices=[('approved', 'Approved'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('hidden', 'Hidden')], max_length=20)),
                ('reason', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('toxicity_score', models.FloatField()),
                ('spam_score', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('moderated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content_authored', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-moderated_at'],
                'indexes': [models.Index(fields=['moderated_by', '-moderated_at'], name='subadmin_mo_moderat_a67016_idx'), models.Index(fields=['content_type', '-moderated_at'], name='subadmin_mo_content_aba334_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('high_toxicity', 'High Toxicity Content'), ('spam_wave', 'Spam Wave Detected'), ('mass_reporting', 'Mass Reporting Activity'), ('ban_evasion', 'Potential Ban Evasion'), ('impersonation', 'Celebrity Impersonation'), ('urgent_kyc', 'Urgent KYC Verification')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('affected_users', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['region', 'is_resolved', '-created_at'], name='subadmin_re_region_4992e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubAdminActivityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reports_data', models.JSONField(default=dict)),
                ('reports_resolved', models.IntegerField(default=0)),
                ('kyc_processed', models.IntegerField(default=0)),
                ('warnings_issued', models.IntegerField(default=0)),
                ('suspensions_issued', models.IntegerField(default=0)),
                ('bans_issued', models.IntegerField(default=0)),
                ('avg_toxicity_score', models.FloatField(default=0)),
                ('avg_spam_score', models.FloatField(default=0)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_reports', to=settings.AUTH_USER_MODEL)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['subadmin', '-submitted_at'], name='subadmin_su_subadmi_567b68_idx'), models.Index(fields=['region', '-submitted_at'], name='subadmin_su_region_382bce_idx')],
            },
        ),
    ]
