# Generated by Django 5.2.7 on 2025-11-05 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModerationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(help_text='Type of content (post, comment, etc.)', max_length=50)),
                ('content_id', models.UUIDField(help_text='ID of the flagged content')),
                ('content_text', models.TextField(help_text='Excerpt of the problematic content')),
                ('alert_type', models.CharField(choices=[('toxicity', 'Toxic Content'), ('spam', 'Spam'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('self_harm', 'Self Harm'), ('explicit', 'Explicit Content')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('toxicity_score', models.FloatField(default=0.0, help_text='AI toxicity score (0-1)')),
                ('toxic_words', models.JSONField(default=list, help_text='List of detected toxic words')),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(default='neutral', max_length=20)),
                ('spam_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warned', 'User Warned'), ('content_removed', 'Content Removed'), ('user_suspended', 'User Suspended'), ('user_banned', 'User Banned')], default='none', max_length=30)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user_previous_violations', models.IntegerField(default=0)),
                ('is_repeat_offender', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'subadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_alerts', to=settings.AUTH_USER_MODEL)),
                ('content_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_alerts_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='subadmin_co_status_ffa3bc_idx'), models.Index(fields=['content_author', 'created_at'], name='subadmin_co_content_c588fd_idx'), models.Index(fields=['assigned_to', 'status'], name='subadmin_co_assigne_83d457_idx')],
            },
        ),
    ]
