# Generated by Django 5.2.7 on 2025-11-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0002_contentmoderationalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminactivityreport',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Detailed feedback from admin'),
        ),
        migrations.AddField(
            model_name='subadminactivityreport',
            name='performance_rating',
            field=models.IntegerField(default=0, help_text='Rating 1-5'),
        ),
        migrations.AddField(
            model_name='subadminactivityreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('needs_improvement', 'Needs Improvement')], default='pending', max_length=20),
        ),
    ]
