# Generated by Django 5.2.7 on 2025-10-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment_label',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Sentiment score from -1 (negative) to 1 (positive)'),
        ),
    ]
