# Generated by Django 5.2.7 on 2025-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_sentiment_label_post_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='merch_category',
            field=models.CharField(blank=True, help_text='Merch category for filtering merch feed', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='related_event_id',
            field=models.UUIDField(blank=True, help_text="Reference to Event if post_type='event'", null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='related_merchandise_id',
            field=models.UUIDField(blank=True, help_text="Reference to Merchandise if post_type='merch'", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('exclusive', 'Exclusive'), ('announcement', 'Announcement'), ('poll', 'Poll'), ('question', 'Question'), ('celebration', 'Celebration'), ('merch', 'Merchandise'), ('event', 'Event')], default='regular', max_length=20),
        ),
    ]
