# Generated by Django 5.2.7 on 2025-11-06 03:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_add_merch_event_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ai_flag_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='ai_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by AI for review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Blocked due to high toxicity'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_label',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Sentiment score from -1 (negative) to 1 (positive)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='spam_score',
            field=models.FloatField(default=0.0, help_text='Spam score 0-1'),
        ),
        migrations.AddField(
            model_name='comment',
            name='toxicity_score',
            field=models.FloatField(default=0.0, help_text='Toxicity score 0-1'),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('nudity', 'Nudity'), ('false_info', 'False Information'), ('offensive', 'Offensive Language'), ('self_harm', 'Self-Harm'), ('scam', 'Scam'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('additional_context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('action_taken', models.CharField(blank=True, choices=[('no_action', 'No Action Taken'), ('warned', 'User Warned'), ('comment_removed', 'Comment Removed'), ('user_suspended', 'User Suspended'), ('user_banned', 'User Banned')], max_length=20)),
                ('action_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.comment')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='posts_comme_status_97c136_idx'), models.Index(fields=['reviewed_by'], name='posts_comme_reviewe_a5580b_idx')],
                'unique_together': {('comment', 'reported_by')},
            },
        ),
    ]
